apiVersion: apps/v1
kind: Deployment
metadata:
  name: steakfulset-controller
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: steakfulset-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: steakfulset-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: steakfulset-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: steakfulset-chef
      automountServiceAccountToken: true
      containers:
      - name: steakfulset-controller
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
