apiVersion: v1
kind: ServiceAccount
metadata:
  name: steakfulset-chef
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: steakfulset-controller
    helm.sh/chart: steakfulset-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: true
