# permissions for end users to edit steakfulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: steakfulset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: steakfulset-controller
    app.kubernetes.io/part-of: steakfulset-controller
    app.kubernetes.io/managed-by: kustomize
  name: steakfulset-editor-role
rules:
- apiGroups:
  - food.k8s.training
  resources:
  - steakfulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - food.k8s.training
  resources:
  - steakfulsets/status
  verbs:
  - get
